[package]
name = "craftql"
version = "0.1.0"
authors = ["yamafaktory <yamafaktory@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
clap = "3.0.0-beta.1"
graphql-parser = "0.3.0"

[dependencies.async-std]
version = "1.6.2"
features = ["attributes", "unstable"]
